### ISSUE TITLE
Can't set power_dpm_state with radcard snippet. And running as root.

### ISSUE THREAD

**Issue by BobbyBabes** [superjamie/snippets#1]
.....

**Comment by superjamie** [comment]
Does the EUID work when you're actually running the script? Which distro are you using?

If I add `echo "EUID = $EUID"` and run under Ubu 16.04 I get:

~~~
$ radcard
EUID = 1000
* [ERROR] Run this script under 'sudo -s' or as root

$ sudo radcard
EUID = 0
Usage: radcard [get|set powerlevel]
~~~

The whole point of EUID is that it's "effective" user ID, it changes under su or sudo. If your distro isn't changing EUID under sudo then I'd suggest it's a distro bug.

**Comment by BobbyBabes** [comment]
I'm using Arch Linux and this is what I see :

![euid-vs-id-u-2](https://cloud.githubusercontent.com/assets/22870070/20888779/91492034-bb00-11e6-8a55-5eb797d9ac88.png)

(I can also not just type ``radcard``. I must type ``./radcard``.)

**Comment by superjamie** [comment]
I can run just `radcard` because I have it in my $PATH.

However, even in pwd, just running `sudo ./radcard` works in both Ubuntu and CentOS. EUID is a widely accepted way to detect if a script or process is running under elevated privileges. If Arch doesn't change EUID under sudo, I suggest this is a bug in Arch.

You're welcome to raise a bug against Arch, or edit your copy of the script, whatever is easiest for you.

**Comment by BobbyBabes** [comment]
So you're not going to respond to my main/real question?

**Comment by superjamie** [comment]
Sorry I didn't realise I had missed anything. I read back and I cannot see what I've not answered. What's the question?

**Comment by BobbyBabes** [comment]
It's above the very first image in the opening post. It belongs together with the first image.

**Comment by superjamie** [comment]
> It seems that the radcard snippet can't change the `power_dpm_state` (to `balanced`).
> Any attempt to set its value also resets the `power_dpm_force_performance_level` to `auto`.

Ah I see, my apologies, I missed that.

I can't imagine that's anything to do with the script, as you can see it's just echoes and cats in sysfs. If the values change unexpectedly then that's nothing the script has done.

This doesn't happen for my HD6870 on Ubuntu with their kernels `4.4.0-51` or `4.8.12`. It's more likely something to do with the `radeon` driver and/or the particular card you have. Ask the driver support/development community: https://www.x.org/wiki/radeon/

There's a channel `#radeon` on Freenode, ask your question then idle for a day or two if nobody answers right away, or you could try the [xorg-driver-ati mailing list](http://lists.x.org/mailman/listinfo/xorg-driver-ati).

Good luck!

**Comment by BobbyBabes** [comment]
I'll do that tomorrow then.
Thanks for your help. Appreciated.
